import DropDownNav from "@/components/navbar/DropDownNav";
import ExploreMoreLayout from "@/components/sidebar/ExploreMoreLayout";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="w-full h-full">
      <div className="">{children}</div>
    </main>
  );
}
